import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    // Nav & Common
    app_name: "AgriVerse",
    tagline: "Smart Farming Ecosystem",
    nav_home: "Home",
    nav_dashboard: "Dashboard",
    nav_marketplace: "Marketplace",
    nav_weather: "Weather",
    nav_scanner: "Leaf Scanner",
    nav_learning: "Learning Center",
    nav_contact: "Contact",
    nav_search: "Search",
    btn_login: "Farmer Login",
    btn_logout: "Logout",
    btn_signup: "Sign Up",
    loading: "Loading...",
    theme_organic: "Organic & Earthy",
    theme_tech: "Modern & Tech-Driven",
    
    // Home Page
    hero_title: "Empowering Farmers with Smart AgTech",
    hero_subtitle: "Predict weather, scan crop diseases, manage tasks, and trade on our local marketplace - all in one unified platform.",
    quick_start: "Quick Actions",
    action_scan: "Scan Leaf",
    action_market: "Visit Market",
    action_weather: "Weather Info",
    intro_title: "Cultivating the Future",
    intro_desc: "AgriVerse brings modern technology to traditional farming. Our ecosystem integrates live environmental data, AI-driven diagnostics, and a decentralized farmer market to optimize your yield and profitability.",

    // Dashboard
    dash_title: "Smart Farm Analytics",
    dash_soil: "Soil Quality Monitoring",
    dash_soil_desc: "Soil pH: 6.5 (Optimal) | Nitrogen: Good | Phosphorus: Medium",
    dash_irrigation: "Irrigation Logs",
    dash_irrigation_desc: "Last watered: 4 hours ago. Next scheduled: Tomorrow 6:00 AM.",
    dash_prediction: "AI Crop Suitability Prediction",
    dash_prediction_desc: "Based on soil & climate, your soil is 94% suitable for Ragi and Tomatoes.",
    dash_tasks: "Farm Chores (To-Do List)",
    task_placeholder: "Enter task name...",
    task_due: "Due Date",
    btn_add_task: "Add Task",
    no_tasks: "No pending tasks! Enjoy your day.",

    // Weather
    weather_title: "Weather Station",
    weather_humidity: "Humidity",
    weather_rainfall: "Rainfall",
    weather_rain_predict: "Rain Forecast",
    weather_alerts: "Critical Alerts",
    weather_no_alerts: "No severe weather warnings in your region.",
    weather_warning_rain: "Heavy rain expected tomorrow. Avoid spraying fertilizer.",

    // Marketplace
    market_title: "Farmer's Marketplace",
    market_subtitle: "Buy and Sell farming tools, seeds, organic fertilizers, and fresh crop produce.",
    market_filter_all: "All Categories",
    market_filter_seeds: "Seeds",
    market_filter_fert: "Fertilizers",
    market_filter_tools: "Farming Tools",
    market_filter_crops: "Crops",
    market_price: "Price",
    market_seller: "Seller",
    market_contact: "Contact",
    market_sell_item: "List Your Product",
    market_prod_name: "Product Name",
    market_category: "Category",
    market_desc: "Description",
    market_list_success: "Product listed successfully!",

    // Leaf Scanner
    scanner_title: "AI Leaf Disease Scanner",
    scanner_subtitle: "Upload an image of a plant leaf to detect diseases, obtain instant organic remedies, and access chemical treatments.",
    scanner_drop: "Click to upload or drag leaf image here",
    scanner_btn: "Analyze Leaf",
    scanner_result: "Diagnostic Report",
    scanner_confidence: "AI Confidence",
    scanner_remedy: "Chemical Remedy",
    scanner_organic: "Organic Treatment",

    // Search
    search_title: "Smart Agriculture Search",
    search_placeholder: "Speak or type crop names, tools, fertilizers...",
    search_mic_listen: "Listening... Speak now.",
    search_mic_error: "Speech recognition not supported in this browser.",
    search_results_crops: "Matching Crops & Diseases",
    search_results_market: "Marketplace Offers",

    // Chatbot
    chat_header: "AgriVerse AI Assistant",
    chat_welcome: "Hello! I am your AgriVerse AI farming helper. Ask me about weather, crop diseases, or marketplace prices.",
    chat_placeholder: "Ask me a question...",

    // FAQ & Contact
    faq_title: "Frequently Asked Questions",
    contact_title: "Contact AgriVerse Support",
    contact_name: "Name",
    contact_email: "Email",
    contact_msg: "Message",
    contact_send: "Send Message",
    contact_success: "Thank you! Our support team will contact you shortly."
  },
  hi: {
    app_name: "एग्रीवर्स",
    tagline: "स्मार्ट फार्मिंग इकोसिस्टम",
    nav_home: "मुख्य पृष्ठ",
    nav_dashboard: "डैशबोर्ड",
    nav_marketplace: "बाजार",
    nav_weather: "मौसम",
    nav_scanner: "पत्ती स्कैनर",
    nav_learning: "शिक्षा केंद्र",
    nav_contact: "संपर्क करें",
    nav_search: "खोजें",
    btn_login: "किसान लॉगिन",
    btn_logout: "लॉगआउट",
    btn_signup: "साइन अप",
    loading: "लोड हो रहा है...",
    theme_organic: "जैविक और प्राकृतिक",
    theme_tech: "आधुनिक और तकनीकी",
    
    hero_title: "स्मार्ट एगटेक से किसानों को सशक्त बनाना",
    hero_subtitle: "मौसम का पूर्वानुमान लगाएं, फसल की बीमारियों को स्कैन करें, कार्यों का प्रबंधन करें और स्थानीय बाजार में व्यापार करें।",
    quick_start: "त्वरित कार्रवाई",
    action_scan: "पत्ती स्कैन करें",
    action_market: "बाजार जाएं",
    action_weather: "मौसम की जानकारी",
    intro_title: "भविष्य की खेती",
    intro_desc: "एग्रीवर्स पारंपरिक खेती में आधुनिक तकनीक लाता है। हमारा इकोसिस्टम लाइव पर्यावरण डेटा, एआई-आधारित निदान और एक विकेंद्रीकृत किसान बाजार को जोड़ता है।",

    dash_title: "स्मार्ट फार्म एनालिटिक्स",
    dash_soil: "मिट्टी की गुणवत्ता की निगरानी",
    dash_soil_desc: "मिट्टी का पीएच: 6.5 (सर्वोत्तम) | नाइट्रोजन: अच्छा | फास्फोरस: मध्यम",
    dash_irrigation: "सिंचाई लॉग",
    dash_irrigation_desc: "आखिरी बार पानी दिया: 4 घंटे पहले। अगला निर्धारित: कल सुबह 6:00 बजे।",
    dash_prediction: "फसल उपयुक्तता पूर्वानुमान",
    dash_prediction_desc: "मिट्टी और जलवायु के आधार पर, आपकी मिट्टी रागी और टमाटर के लिए 94% उपयुक्त है।",
    dash_tasks: "खेत के काम (कार्य सूची)",
    task_placeholder: "कार्य का नाम दर्ज करें...",
    task_due: "नियत तारीख",
    btn_add_task: "कार्य जोड़ें",
    no_tasks: "कोई काम लंबित नहीं है! अपने दिन का आनंद लें।",

    weather_title: "मौसम केंद्र",
    weather_humidity: "आर्द्रता",
    weather_rainfall: "वर्षा",
    weather_rain_predict: "बारिश का पूर्वानुमान",
    weather_alerts: "महत्वपूर्ण अलर्ट",
    weather_no_alerts: "आपके क्षेत्र में कोई गंभीर मौसम की चेतावनी नहीं है।",
    weather_warning_rain: "कल भारी बारिश की संभावना है। उर्वरक का छिड़काव न करें।",

    market_title: "किसान बाजार",
    market_subtitle: "खेती के उपकरण, बीज, जैविक खाद और ताजी फसल खरीदें और बेचें।",
    market_filter_all: "सभी श्रेणियां",
    market_filter_seeds: "बीज",
    market_filter_fert: "उर्वरक",
    market_filter_tools: "कृषि उपकरण",
    market_filter_crops: "फसलें",
    market_price: "कीमत",
    market_seller: "विक्रेता",
    market_contact: "संपर्क करें",
    market_sell_item: "अपना उत्पाद सूचीबद्ध करें",
    market_prod_name: "उत्पाद का नाम",
    market_category: "श्रेणी",
    market_desc: "विवरण",
    market_list_success: "उत्पाद सफलतापूर्वक सूचीबद्ध किया गया!",

    scanner_title: "एआई पत्ती रोग स्कैनर",
    scanner_subtitle: "बीमारियों का पता लगाने, तत्काल जैविक उपचार प्राप्त करने और रासायनिक उपचार तक पहुंचने के लिए पौधे की पत्ती की छवि अपलोड करें।",
    scanner_drop: "अपलोड करने के लिए क्लिक करें या पत्ती की छवि को यहां खींचें",
    scanner_btn: "पत्ती का विश्लेषण करें",
    scanner_result: "नैदानिक रिपोर्ट",
    scanner_confidence: "एआई सटीकता",
    scanner_remedy: "रासायनिक उपचार",
    scanner_organic: "जैविक उपचार",

    search_title: "स्मार्ट कृषि खोज",
    search_placeholder: "फसलों के नाम, उपकरण, उर्वरक बोलें या टाइप करें...",
    search_mic_listen: "सुन रहा हूँ... अब बोलिए।",
    search_mic_error: "इस ब्राउज़र में भाषण पहचान समर्थित नहीं है।",
    search_results_crops: "मिलती-जुलती फसलें और बीमारियां",
    search_results_market: "बाजार के ऑफर",

    chat_header: "एग्रीवर्स एआई सहायक",
    chat_welcome: "नमस्ते! मैं आपका एग्रीवर्स एआई कृषि सहायक हूं। मुझसे मौसम, फसल की बीमारियों या बाजार की कीमतों के बारे में पूछें।",
    chat_placeholder: "मुझसे कोई प्रश्न पूछें...",

    faq_title: "अक्सर पूछे जाने वाले प्रश्न",
    contact_title: "एग्रीवर्स सहायता से संपर्क करें",
    contact_name: "नाम",
    contact_email: "ईमेल",
    contact_msg: "संदेश",
    contact_send: "संदेश भेजें",
    contact_success: "धन्यवाद! हमारी सहायता टीम जल्द ही आपसे संपर्क करेगी।"
  },
  te: {
    app_name: "అగ్రివర్స్",
    tagline: "స్మార్ట్ ఫార్మింగ్ పర్యావరణ వ్యవస్థ",
    nav_home: "హోమ్",
    nav_dashboard: "డ్యాష్‌బోర్డ్",
    nav_marketplace: "మార్కెట్ ప్లేస్",
    nav_weather: "వాతావరణం",
    nav_scanner: "లీఫ్ స్కానర్",
    nav_learning: "లెర్నింగ్ సెంటర్",
    nav_contact: "సంప్రదించండి",
    nav_search: "సెర్చ్",
    btn_login: "రైతు లాగిన్",
    btn_logout: "లాగౌట్",
    btn_signup: "సైన్ అప్",
    loading: "లోడ్ అవుతోంది...",
    theme_organic: "ఆర్గానిక్ & మట్టి రంగు",
    theme_tech: "ఆధునిక & సాంకేతిక",
    
    hero_title: "స్మార్ట్ అగ్‌టెక్‌తో రైతుల సాధికారత",
    hero_subtitle: "వాతావరణాన్ని అంచనా వేయండి, పంట తెగుళ్లను స్కాన్ చేయండి, పనులను నిర్వహించండి మరియు స్థానిక మార్కెట్లో వ్యాపారం చేయండి.",
    quick_start: "శీఘ్ర చర్యలు",
    action_scan: "ఆకును స్కాన్ చేయండి",
    action_market: "మార్కెట్ సందర్శించండి",
    action_weather: "వాతావరణ సమాచారం",
    intro_title: "వ్యవసాయ భవిష్యత్తు",
    intro_desc: "అగ్రివర్స్ సాంప్రదాయ వ్యవసాయంలోకి ఆధునిక సాంకేతికతను తెస్తుంది. మా పర్యావరణ వ్యవస్థ పర్యావరణ డేటా, కృత్రిమ మేధస్సు మరియు వికేంద్రీకృత రైతు మార్కెట్‌ను అనుసంధానిస్తుంది.",

    dash_title: "స్మార్ట్ ఫార్మ్ అనలిటిక్స్",
    dash_soil: "నేల నాణ్యత పర్యవేక్షణ",
    dash_soil_desc: "నేల pH: 6.5 (అత్యుత్తమం) | నైట్రోజన్: బాగుంది | భాస్వరం: మధ్యమం",
    dash_irrigation: "నీటిపారుదల లాగ్‌లు",
    dash_irrigation_desc: "చివరిగా నీరు పోసింది: 4 గంటల క్రితం. తదుపరి షెడ్యూల్: రేపు ఉదయం 6:00 గంటలకు.",
    dash_prediction: "పంట అనుకూలత అంచనా",
    dash_prediction_desc: "నేల & వాతావరణం ఆధారంగా, మీ నేల రాగులు మరియు టమోటాలకు 94% అనుకూలంగా ఉంది.",
    dash_tasks: "వ్యవసాయ పనులు (చేయవలసిన పనుల జాబితా)",
    task_placeholder: "పని పేరును నమోదు చేయండి...",
    task_due: "గడువు తేదీ",
    btn_add_task: "పనిని జోడించు",
    no_tasks: "పెండింగ్ పనులు లేవు! ఈ రోజును ఆనందించండి.",

    weather_title: "వాతావరణ కేంద్రం",
    weather_humidity: "తేమ",
    weather_rainfall: "వర్షపాతం",
    weather_rain_predict: "వర్షం అంచనా",
    weather_alerts: "ముఖ్యమైన హెచ్చరికలు",
    weather_no_alerts: "మీ ప్రాంతంలో తీవ్రమైన వాతావరణ హెచ్చరికలు లేవు.",
    weather_warning_rain: "రేపు భారీ వర్షం పడే అవకాశం ఉంది. ఎరువులు చల్లడం నివారించండి.",

    market_title: "రైతు మార్కెట్",
    market_subtitle: "వ్యవసాయ పనిముట్లు, విత్తనాలు, సేంద్రీయ ఎరువులు మరియు తాజా పంట ఉత్పత్తులను కొనండి మరియు అమ్మండి.",
    market_filter_all: "అన్ని వర్గాలు",
    market_filter_seeds: "విత్తనాలు",
    market_filter_fert: "ఎరువులు",
    market_filter_tools: "వ్యవసాయ పనిముట్లు",
    market_filter_crops: "పంటలు",
    market_price: "ధర",
    market_seller: "అమ్మకందారుడు",
    market_contact: "సంప్రదించండి",
    market_sell_item: "మీ ఉత్పత్తిని జాబితా చేయండి",
    market_prod_name: "ఉత్పత్తి పేరు",
    market_category: "వర్గం",
    market_desc: "వివరణ",
    market_list_success: "ఉత్పత్తి విజయవంతంగా జాబितా చేయబడింది!",

    scanner_title: "AI లీఫ్ తెగులు స్కానర్",
    scanner_subtitle: "తెగుళ్లను గుర్తించడానికి, తక్షణ సేంద్రీయ నివారణలను పొందడానికి మరియు రసాయన చికిత్సలను యాక్సెస్ చేయడానికి ఆకు చిత్రాన్ని అప్‌లోడ్ చేయండి.",
    scanner_drop: "అప్‌లోడ్ చేయడానికి క్లిక్ చేయండి లేదా ఆకు చిత్రాన్ని ఇక్కడికి లాగండి",
    scanner_btn: "ఆకును విశ్లేషించండి",
    scanner_result: "రోగనిర్ధారణ నివేదిక",
    scanner_confidence: "AI ఖచ్చితత్వం",
    scanner_remedy: "రసాయన నివారణ",
    scanner_organic: "సేంద్రీయ చికిత్స",

    search_title: "స్మార్ట్ వ్యవసాయ శోధన",
    search_placeholder: "పంటల పేర్లు, పరికరాలు, ఎరువులు మాట్లాడండి లేదా టైప్ చేయండి...",
    search_mic_listen: "వింటున్నాను... ఇప్పుడు మాట్లాడండి.",
    search_mic_error: "ఈ బ్రౌజర్‌లో స్పీచ్ రికగ్నిషన్ సపోర్ట్ చేయదు.",
    search_results_crops: "సరిపోలే పంటలు & తెగుళ్లు",
    search_results_market: "మార్కెట్ ప్లేస్ ఆఫర్లు",

    chat_header: "అగ్రివర్స్ AI సహాయకుడు",
    chat_welcome: "నమస్కారం! నేను మీ అగ్రివర్స్ AI సహాయకుడిని. వాతావరణం, పంట తెగుళ్లు లేదా మార్కెట్ ధరల గురించి నన్ను అడగండి.",
    chat_placeholder: "నన్ను ఒక ప్రశ్న అడగండి...",

    faq_title: "తరచుగా అడిగే ప్రశ్నలు",
    contact_title: "అగ్రివర్స్ మద్దతును సంప్రదించండి",
    contact_name: "పేరు",
    contact_email: "ఇమెయిల్",
    contact_msg: "సందేశం",
    contact_send: "సందేశాన్ని పంపండి",
    contact_success: "ధన్యవాదాలు! మా సహాయక బృందం త్వరలో మిమ్మల్ని సంప్రదిస్తుంది."
  },
  ta: {
    app_name: "அகிரிவெர்ஸ்",
    tagline: "ஸ்மார்ட் விவசாய சுற்றுச்சூழல்",
    nav_home: "முகப்பு",
    nav_dashboard: "டாஷ்போர்டு",
    nav_marketplace: "சந்தை",
    nav_weather: "வானிலை",
    nav_scanner: "இலை ஸ்கேனர்",
    nav_learning: "கற்றல் மையம்",
    nav_contact: "தொடர்பு",
    nav_search: "தேடல்",
    btn_login: "விவசாயி உள்நுழைவு",
    btn_logout: "வெளியேறு",
    btn_signup: "பதிவு செய்க",
    loading: "ஏற்றப்படுகிறது...",
    theme_organic: "இயற்கை & மண்வளம்",
    theme_tech: "நவீன & தொழில்நுட்பம்",
    hero_title: "ஸ்மார்ட் அக்-டெக் மூலம் விவசாயிகளை மேம்படுத்துதல்",
    hero_subtitle: "வானிலை கணிப்பு, இலை நோய் கண்டறிதல், பணிகள் மேலாண்மை மற்றும் உள்ளூர் சந்தை வியாபாரம் - அனைத்தும் ஒரே தளத்தில்.",
    quick_start: "விரைவு செயல்பாடுகள்",
    action_scan: "இலை ஸ்கேன்",
    action_market: "சந்தைக்குச் செல்",
    action_weather: "வானிலை தகவல்",
    intro_title: "ಎದುರ್ಕಾಲ ವಿವಾಸಯಮ್",
    intro_desc: "அகிரிவெர்ஸ் பாரம்பரிய விவசாயத்திற்கு நவீன தொழில்நுட்பத்தை வழங்குகிறது. பயிர் உற்பத்தியை அதிகரிக்க நேரடி வானிலை தரவுகள், AI கண்டறிதல் மற்றும் விவசாய சந்தை ஆகியவற்றை இணைக்கிறோம்.",
    dash_title: "ಸ್ಮಾರ್ಟ್ பண்ணை பகுப்பாய்வு",
    dash_soil: "மண் தரம் கண்காணிப்பு",
    dash_soil_desc: "மண் pH: 6.5 (உகந்தது) | நைட்ரஜன்: நன்று | பாஸ்பரஸ்: நடுத்தரம்",
    dash_irrigation: "நீர் மேலாண்மை",
    dash_irrigation_desc: "கடைசியாக நீர் பாய்ச்சியது: 4 மணி நேரம் முன்பு. அடுத்த அட்டவணை: நாளை காலை 6:00 மணி.",
    dash_prediction: "AI பயிர் பொருத்த கணிப்பு",
    dash_prediction_desc: "மண் மற்றும் காலநிலை அடிப்படையில், உங்கள் மண் கேழ்வரகு மற்றும் தக்காளிக்கு 94% உகந்தது.",
    dash_tasks: "பண்ணை பணிகள் (செய்ய வேண்டியவை)",
    task_placeholder: "பணியின் பெயரை உள்ளிடவும்...",
    task_due: "கடைசி தேதி",
    btn_add_task: "பணியைச் சேர்",
    no_tasks: "பெண்டிங் பணிகள் இல்லை! மகிழுங்கள்.",
    weather_title: "வானிலை நிலையம்",
    weather_humidity: "ஈரப்பதம்",
    weather_rainfall: "மழைப்பொழிவு",
    weather_rain_predict: "மழை கணிப்பு",
    weather_alerts: "முக்கிய எச்சரிக்கைகள்",
    weather_no_alerts: "உங்கள் பகுதியில் கடுமையான வானிலை எச்சரிக்கைகள் எதுவும் இல்லை.",
    weather_warning_rain: "நாளை கனமழை பெய்யக்கூடும். உரங்கள் தெளிப்பதைத் தவிர்க்கவும்.",
    market_title: "விவசாயிகள் சந்தை",
    market_subtitle: "விவசாய கருவிகள், விதைகள், இயற்கை உரங்கள் மற்றும் புதிய பயிர்களை வாங்கவும் விற்கவும்.",
    market_filter_all: "அனைத்து பிரிவுகள்",
    market_filter_seeds: "விதைகள்",
    market_filter_fert: "உரங்கள்",
    market_filter_tools: "விவசாய கருவிகள்",
    market_filter_crops: "பயிர்கள்",
    market_price: "விலை",
    market_seller: "விற்பனையாளர்",
    market_contact: "தொடர்பு எண்",
    market_sell_item: "பொருளை பட்டியலிடு",
    market_prod_name: "தயாரிப்பு பெயர்",
    market_category: "வகை",
    market_desc: "விளக்கம்",
    market_list_success: "தயாரிப்பு வெற்றிகரமாக பட்டியலிடப்பட்டது!",
    scanner_title: "AI இலை நோய் ஸ்கேனர்",
    scanner_subtitle: "இலை நோய்களைக் கண்டறிந்து, உடனடி இயற்கை மற்றும் வேதியியல் தீர்வுகளைப் பெற பயிர் இலையின் படத்தை பதிவேற்றவும்.",
    scanner_drop: "பதிவேற்ற கிளிக் செய்யவும் அல்லது இலையின் படத்தை இங்கே இழுத்து விடவும்",
    scanner_btn: "இலையை பகுப்பாய்வு செய்",
    scanner_result: "கண்டறியும் அறிக்கை",
    scanner_confidence: "AI துல்லியம்",
    scanner_remedy: "வேதியியல் தீர்வு",
    scanner_organic: "இயற்கை சிகிச்சை",
    search_title: "ஸ்மார்ட் விவசாய தேடல்",
    search_placeholder: "பயிர்கள், கருவிகள், உரங்கள் பற்றி பேசவும் அல்லது தட்டச்சு செய்யவும்...",
    search_mic_listen: "கேட்கிறது... இப்போது பேசவும்.",
    search_mic_error: "இந்த உலாவியில் குரல் அங்கீகாரம் ஆதரிக்கப்படவில்லை.",
    search_results_crops: "பொருந்தும் பயிர்கள் & நோய்கள்",
    search_results_market: "சந்தை சலுகைகள்",
    chat_header: "அகிரிவெர்ஸ் AI உதவியாளர்",
    chat_welcome: "வணக்கம்! நான் உங்கள் அகிரிவெர்ஸ் AI விவசாய உதவியாளர். வானிலை, இலை நோய்கள் அல்லது சந்தை விலைகள் பற்றி என்னிடம் கேட்கலாம்.",
    chat_placeholder: "கேள்வி கேளுங்கள்...",
    faq_title: "அடிக்கடி கேட்கப்படும் கேள்விகள்",
    contact_title: "அகிரிவெர்ஸ் ஆதரவைத் தொடர்பு கொள்ளவும்",
    contact_name: "பெயர்",
    contact_email: "மின்னஞ்சல்",
    contact_msg: "செய்தி",
    contact_send: "செய்தி அனுப்பு",
    contact_success: "நன்றி! எங்கள் ஆதரவு குழு விரைவில் உங்களை தொடர்பு கொள்ளும்."
  },
  kn: {
    app_name: "ಅಗ್ರಿವರ್ಸ್",
    tagline: "ಸ್ಮಾರ್ಟ್ ಕೃಷಿ ಪರಿಸರ ವ್ಯವಸ್ಥೆ",
    nav_home: "ಮುಖಪುಟ",
    nav_dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    nav_marketplace: "ಮಾರುಕಟ್ಟೆ",
    nav_weather: "ಹವಾಮಾನ",
    nav_scanner: "ಎಲೆ ಸ್ಕ್ಯಾನರ್",
    nav_learning: "ಕಲಿಕಾ ಕೇಂದ್ರ",
    nav_contact: "ಸಂಪರ್ಕಿಸಿ",
    nav_search: "ಹುಡುಕಾಟ",
    btn_login: "ರೈತರ ಲಾಗಿನ್",
    btn_logout: "ಲಾಗ್ ಔಟ್",
    btn_signup: "ನೋಂದಾಯಿಸಿ",
    loading: "ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
    theme_organic: "ಸಾವಯವ ಮತ್ತು ಮಣ್ಣಿನ ಬಣ್ಣ",
    theme_tech: "ನವೀನ ಮತ್ತು ತಾಂತ್ರಿಕ",
    hero_title: "ಸ್ಮಾರ್ಟ್ ಅಗ್ಟೆಕ್ ಮೂಲಕ ರೈತರ ಸಬಲೀಕರಣ",
    hero_subtitle: "ಹವಾಮಾನ ಮುನ್ಸೂಚನೆ, ಎಲೆ ರೋಗ ಪತ್ತೆ ಹಚ್ಚಿ, ಕೆಲಸಗಳನ್ನು ನಿರ್ವಹಿಸಿ ಮತ್ತು ಸ್ಥಳೀಯ ಮಾರುಕಟ್ಟೆಯಲ್ಲಿ ವ್ಯಾಪಾರ ಮಾಡಿ.",
    quick_start: "ಶೀಘ್ರ ಕ್ರಿಯೆಗಳು",
    action_scan: "ಎಲೆ ಸ್ಕ್ಯಾನ್",
    action_market: "ಮಾರುಕಟ್ಟೆಗೆ ಭೇಟಿ ಕೊಡಿ",
    action_weather: "ಹವಾಮಾನ ಮಾಹಿತಿ",
    intro_title: "ಭವಿಷ್ಯದ ಕೃಷಿ",
    intro_desc: "ಅಗ್ರಿವರ್ಸ್ ಸಾಂಪ್ರದಾಯಿಕ ಕೃಷಿಗೆ ಆಧುನಿಕ ತಂತ್ರಜ್ಞಾನವನ್ನು ತರುತ್ತದೆ. ಬೆಳೆ ಇಳುವರಿಯನ್ನು ಹೆಚ್ಚಿಸಲು ನಾವು ಹವಾಮಾನ ಡೇಟಾ ಮತ್ತು ಕೃಷಿ ಮಾರುಕಟ್ಟೆಯನ್ನು ಸಂಯೋಜಿಸುತ್ತೇವೆ.",
    dash_title: "ಸ್ಮಾರ್ಟ್ ಕೃಷಿ ವಿಶ್ಲೇಷಣೆ",
    dash_soil: "ಮಣ್ಣಿನ ಗುಣಮಟ್ಟ ಮೇಲ್ವಿಚಾರಣೆ",
    dash_soil_desc: "ಮಣ್ಣಿನ pH: 6.5 (ಉತ್ತಮ) | ಸಾರಜನಕ: ಚೆನ್ನಾಗಿದೆ | ರಂಜಕ: ಮಧ್ಯಮ",
    dash_irrigation: "ನೀರಾವರಿ ದಾಖಲೆಗಳು",
    dash_irrigation_desc: "ಕೊನೆಯದಾಗಿ ನೀರುಣಿಸಿದ್ದು: 4 ಗಂಟೆಗಳ ಹಿಂದೆ. ಮುಂದಿನ ವೇಳಾಪಟ್ಟಿ: ನಾಳೆ ಬೆಳಿಗ್ಗೆ 6:00.",
    dash_prediction: "AI ಬೆಳೆ ಹೊಂದಾಣಿಕೆ ಮುನ್ಸೂಚನೆ",
    dash_prediction_desc: "ಮಣ್ಣು ಮತ್ತು ಹವಾಮಾನದ ಆಧಾರದ ಮೇಲೆ, ನಿಮ್ಮ ಮಣ್ಣು ರಾಗಿ ಮತ್ತು ಟೊಮೆಟೊಗೆ 94% ಸೂಕ್ತವಾಗಿದೆ.",
    dash_tasks: "ಕೃಷಿ ಕೆಲಸಗಳು (ಮಾಡಬೇಕಾದ ಪಟ್ಟಿ)",
    task_placeholder: "ಕೆಲಸದ ಹೆಸರನ್ನು ನಮೂದಿಸಿ...",
    task_due: "ಕೊನೆಯ ದಿನಾಂಕ",
    btn_add_task: "ಕೆಲಸವನ್ನು ಸೇರಿಸಿ",
    no_tasks: "ಯಾವುದೇ ಕೆಲಸ ಬಾಕಿ ಇಲ್ಲ! ದಿನವನ್ನು ಆನಂದಿಸಿ.",
    weather_title: "ಹವಾಮಾನ ಕೇಂದ್ರ",
    weather_humidity: "ಆರ್ದ್ರತೆ",
    weather_rainfall: "ಮಳೆ ಪ್ರಮಾಣ",
    weather_rain_predict: "ಮಳೆ ಮುನ್ಸೂಚನೆ",
    weather_alerts: "ಪ್ರಮುಖ ಎಚ್ಚರಿಕೆಗಳು",
    weather_no_alerts: "ನಿಮ್ಮ ಪ್ರದೇಶದಲ್ಲಿ ಯಾವುದೇ ಹವಾಮಾನ ಮುನ್ಸೂಚನೆ ಎಚ್ಚರಿಕೆಗಳಿಲ್ಲ.",
    weather_warning_rain: "ನಾಳೆ ಭಾರಿ ಮಳೆಯಾಗುವ ಸಾಧ್ಯತೆಯಿದೆ. ರಸಗೊಬ್ಬರ ಸಿಂಪಡಿಸಬೇಡಿ.",
    market_title: "ರೈತರ ಮಾರುಕಟ್ಟೆ",
    market_subtitle: "ಕೃಷಿ ಉಪಕರಣಗಳು, ಬೀಜಗಳು, ಸಾವಯವ ಗೊಬ್ಬರಗಳು ಮತ್ತು ತಾಜಾ ಬೆಳೆಗಳನ್ನು ಖರೀದಿಸಿ ಮತ್ತು ಮಾರಾಟ ಮಾಡಿ.",
    market_filter_all: "ಎಲ್ಲಾ ವಿಭಾಗಗಳು",
    market_filter_seeds: "ಬೀಜಗಳು",
    market_filter_fert: "ಗೊಬ್ಬರಗಳು",
    market_filter_tools: "ಕೃಷಿ ಉಪಕರಣಗಳು",
    market_filter_crops: "ಬೆಳೆಗಳು",
    market_price: "ಬೆಲೆ",
    market_seller: "ಮಾರಾಟಗಾರರು",
    market_contact: "ಸಂಪರ್ಕಿಸಿ",
    market_sell_item: "ಉತ್ಪನ್ನವನ್ನು ಪಟ್ಟಿ ಮಾಡಿ",
    market_prod_name: "ಉತ್ಪನ್ನದ ಹೆಸರು",
    market_category: "ವರ್ಗ",
    market_desc: "ವಿವರಣೆ",
    market_list_success: "ಉತ್ಪನ್ನವನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಪಟ್ಟಿ ಮಾಡಲಾಗಿದೆ!",
    scanner_title: "AI ಎಲೆ ರೋಗ ಸ್ಕ್ಯಾನರ್",
    scanner_subtitle: "ಎಲೆ ರೋಗಗಳನ್ನು ಪತ್ತೆಹಚ್ಚಲು ಮತ್ತು ಸಾವಯವ ಪರಿಹಾರಗಳನ್ನು ಪಡೆಯಲು ಎಲೆಯ ಚಿತ್ರವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.",
    scanner_drop: "ಅಪ್‌ಲೋಡ್ ಮಾಡಲು ಕ್ಲಿಕ್ ಮಾಡಿ ಅಥವಾ ಎಲೆಯ ಚಿತ್ರವನ್ನು ಇಲ್ಲಿಗೆ ಎಳೆಯಿರಿ",
    scanner_btn: "ಎಲೆಯನ್ನು ವಿಶ್ಲೇಷಿಸಿ",
    scanner_result: "ರೋಗನಿರ್ಣಯ ವರದಿ",
    scanner_confidence: "AI ಖಚಿತತೆ",
    scanner_remedy: "ರಾಸಾಯನಿಕ ಪರಿಹಾರ",
    scanner_organic: "ಸಾವಯವ ಚಿಕಿತ್ಸೆ",
    search_title: "ಸ್ಮಾರ್ಟ್ ಕೃಷಿ ಹುಡುಕಾಟ",
    search_placeholder: "ಬೆಳೆಗಳು, ಉಪಕರಣಗಳು ಅಥವಾ ಗೊಬ್ಬರಗಳ ಹೆಸರನ್ನು ಹೇಳಿ ಅಥವಾ ಬರೆಯಿರಿ...",
    search_mic_listen: "ಕೇಳಿಸಿಕೊಳ್ಳುತ್ತಿದೆ... ಈಗ ಮಾತನಾಡಿ.",
    search_mic_error: "ಈ ಬ್ರೌಸರ್‌ನಲ್ಲಿ ಧ್ವನಿ ಗುರುತಿಸುವಿಕೆ ಬೆಂಬಲಿಸುವುದಿಲ್ಲ.",
    search_results_crops: "ಹೊಂದುವ ಬೆಳೆಗಳು ಮತ್ತು ರೋಗಗಳು",
    search_results_market: "ಮಾರುಕಟ್ಟೆ ಕೊಡುಗೆಗಳು",
    chat_header: "ಅಗ್ರಿವರ್ಸ್ AI ಸಹಾಯಕಿ",
    chat_welcome: "ನಮಸ್ಕಾರ! ನಾನು ನಿಮ್ಮ ಅಗ್ರಿವರ್ಸ್ ಕೃಷಿ ಸಹಾಯಕಿ. ಹವಾಮಾನ, ಎಲೆ ರೋಗಗಳು ಅಥವಾ ಮಾರುಕಟ್ಟೆ ಬೆಲೆಗಳ ಬಗ್ಗೆ ಕೇಳಿ.",
    chat_placeholder: "ನನಗೊಂದು ಪ್ರಶ್ನೆ ಕೇಳಿ...",
    faq_title: "ಪದೇ ಪದೇ ಕೇಳಲಾಗುವ ಪ್ರಶ್ನೆಗಳು",
    contact_title: "ಅಗ್ರಿವರ್ಸ್ ಬೆಂಬಲವನ್ನು ಸಂಪರ್ಕಿಸಿ",
    contact_name: "ಹೆಸರು",
    contact_email: "ಇಮೇಲ್",
    contact_msg: "ಸಂದೇಶ",
    contact_send: "ಸಂದೇಶ ಕಳುಹಿಸಿ",
    contact_success: "ಧನ್ಯವಾದಗಳು! ನಮ್ಮ ತಂಡ ಶೀಘ್ರದಲ್ಲೇ ಸಂಪರ್ಕಿಸುತ್ತದೆ."
  },
  mr: {
    app_name: "एग्रीव्हर्स",
    tagline: "स्मार्ट शेती परिसंस्था",
    nav_home: "मुख्यपृष्ठ",
    nav_dashboard: "डॅशबोर्ड",
    nav_marketplace: "बाजारपेठ",
    nav_weather: "हवामान",
    nav_scanner: "पान स्कॅनर",
    nav_learning: "शिक्षण केंद्र",
    nav_contact: "संपर्क साधा",
    nav_search: "शोध",
    btn_login: "शेतकरी लॉगिन",
    btn_logout: "लॉगआउट",
    btn_signup: "नोंदणी करा",
    loading: "लोड होत आहे...",
    theme_organic: "सेंद्रिय आणि माती रंग",
    theme_tech: "आधुनिक आणि तांत्रिक",
    hero_title: "स्मार्ट एगटेक द्वारे शेतकऱ्यांचे सक्षमीकरण",
    hero_subtitle: "हवामानाचा अंदाज घ्या, पिकांचे आजार स्कॅन करा, कामे व्यवस्थापित करा आणि बाजारात थेट व्यापार करा.",
    quick_start: "त्वरित कृती",
    action_scan: "पान स्कॅन",
    action_market: "बाजाराला भेट द्या",
    action_weather: "हवामान माहिती",
    intro_title: "भविष्यातील शेती",
    intro_desc: "एग्रीव्हर्स पारंपारिक शेतीमध्ये आधुनिक तंत्रज्ञान आणते. पीक उत्पादकता सुधारण्यासाठी आम्ही हवामान डेटा आणि शेतकरी बाजार एकत्रित करतो.",
    dash_title: "स्मार्ट शेती विश्लेषण",
    dash_soil: "माती गुणवत्ता नियंत्रण",
    dash_soil_desc: "माती पीएच: ६.५ (उत्कृष्ट) | नायट्रोजन: चांगले | फॉस्फरस: मध्यम",
    dash_irrigation: "सिंचन नोंदी",
    dash_irrigation_desc: "शेवटचे पाणी दिले: ४ तासांपूर्वी. पुढील नियोजन: उद्या सकाळी ६:०० वाजता.",
    dash_prediction: "AI पीक अनुकूलता अंदाज",
    dash_prediction_desc: "माती आणि हवामानानुसार, तुमची जमीन रागी आणि टोमॅटोसाठी ९४% योग्य आहे.",
    dash_tasks: "शेतीची कामे (कार्य सूची)",
    task_placeholder: "कामाचे नाव टाका...",
    task_due: "नियत तारीख",
    btn_add_task: "काम जोडा",
    no_tasks: "काहीही काम प्रलंबित नाही! आनंदी राहा.",
    weather_title: "हवामान केंद्र",
    weather_humidity: "आर्द्रता",
    weather_rainfall: "पाऊस",
    weather_rain_predict: "पावसाचा अंदाज",
    weather_alerts: "महत्त्वाच्या सूचना",
    weather_no_alerts: "तुमच्या भागात हवामानाची कोणतीही गंभीर चेतावणी नाही.",
    weather_warning_rain: "उद्या मुसळधार पावसाची शक्यता आहे. खतांची फवारणी टाळा.",
    market_title: "शेतकरी बाजार",
    market_subtitle: "शेतीची अवजारे, बियाणे, सेंद्रिय खते आणि ताजी पिके खरेदी करा व विक्री करा.",
    market_filter_all: "सर्व प्रकार",
    market_filter_seeds: "बियाणे",
    market_filter_fert: "खते",
    market_filter_tools: "शेतीची अवजारे",
    market_filter_crops: "पिके",
    market_price: "किंमत",
    market_seller: "विक्रेता",
    market_contact: "संपर्क",
    market_sell_item: "उत्पादनाची नोंद करा",
    market_prod_name: "उत्पादनाचे नाव",
    market_category: "वर्ग",
    market_desc: "वर्णन",
    market_list_success: "उत्पादन यशस्वीरित्या नोंदवले गेले!",
    scanner_title: "AI पान रोग स्कॅनर",
    scanner_subtitle: "पानावरील रोगांचे निदान करण्यासाठी आणि सेंद्रिय उपाय मिळवण्यासाठी पानाचा फोटो अपलोड करा.",
    scanner_drop: "अपलोड करण्यासाठी क्लिक करा किंवा पानाचा फोटो येथे खेचा",
    scanner_btn: "पान विश्लेषण करा",
    scanner_result: "निदान अहवाल",
    scanner_confidence: "AI अचूकता",
    scanner_remedy: "रासायनिक उपाय",
    scanner_organic: "सेंद्रिय उपाय",
    search_title: "स्मार्ट शेती शोध",
    search_placeholder: "पिके किंवा खतांचे नाव बोला अथवा टाईप करा...",
    search_mic_listen: "ऐकत आहे... आता बोला.",
    search_mic_error: "या ब्राउझरमध्ये आवाज ओळखणे समर्थित नाही.",
    search_results_crops: "जुळणारी पिके आणि रोग",
    search_results_market: "बाजारपेठ ऑफर्स",
    chat_header: "एग्रीव्हर्स AI मदतनीस",
    chat_welcome: "नमस्कार! मी आपला एग्रीव्हर्स AI शेती मदतनीस आहे. मला हवामान, पानांचे रोग किंवा बाजारातील किमतींबद्दल विचारा.",
    chat_placeholder: "मला प्रश्न विचारा...",
    faq_title: "वारंवार विचारले जाणारे प्रश्न",
    contact_title: "एग्रीव्हर्स सपोर्टशी संपर्क साधा",
    contact_name: "नाव",
    contact_email: "ईमेल",
    contact_msg: "संदेश",
    contact_send: "संदेश पाठवा",
    contact_success: "धन्यवाद! आमची मदत चमू लवकरच तुमच्याशी संपर्क साधेल."
  },
  bn: {
    app_name: "এগ্রিভার্স",
    tagline: "স্মার্ট কৃষি ইকোসিস্টেম",
    nav_home: "মূল পাতা",
    nav_dashboard: "ড্যাশবোর্ড",
    nav_marketplace: "বাজার",
    nav_weather: "আবহাওয়া",
    nav_scanner: "পাতা স্ক্যানার",
    nav_learning: "শিক্ষা কেন্দ্র",
    nav_contact: "যোগাযোগ",
    nav_search: "অনুসন্ধান",
    btn_login: "কৃষক লগইন",
    btn_logout: "লগআউট",
    btn_signup: "নিবন্ধন করুন",
    loading: "লোড হচ্ছে...",
    theme_organic: "জৈব এবং মাটির রঙ",
    theme_tech: "আধুনিক এবং প্রযুক্তিগত",
    hero_title: "স্মার্ট এগ্রিটেক দিয়ে কৃষকদের ক্ষমতায়ন",
    hero_subtitle: "আবহাওয়ার পূর্বাভাস জানুন, পাতার রোগ স্ক্যান করুন, কাজ পরিচালনা করুন এবং কেনাবেচা করুন।",
    quick_start: "দ্রুত লিংক",
    action_scan: "পাতা স্ক্যান",
    action_market: "বাজার পরিদর্শন",
    action_weather: "আবহাওয়ার তথ্য",
    intro_title: "ভবিষ্যতের কৃষি",
    intro_desc: "এগ্রিভার্স প্রথাগত কৃষিতে আধুনিক প্রযুক্তি নিয়ে আসে। ফলন বাড়াতে আমরা আবহাওয়া ডেটা এবং উন্মুক্ত বাজারকে সংযুক্ত করি।",
    dash_title: "স্মার্ট কৃষি বিশ্লেষণ",
    dash_soil: "মাটি পরীক্ষা ও পর্যবেক্ষণ",
    dash_soil_desc: "মাটির pH: ৬.৫ (সেরা) | নাইট্রোজেন: ভালো | ফসফরাস: মাঝারি",
    dash_irrigation: "সেচের বিবরণ",
    dash_irrigation_desc: "সর্বশেষ সেচ: ৪ ঘণ্টা আগে। পরবর্তী সময়সূচী: আগামীকাল সকাল ৬:০০ টা।",
    dash_prediction: "AI ফসল উপযুক্ততা পূর্বাভাস",
    dash_prediction_desc: "মাটি এবং জলবায়ুর ওপর ভিত্তি করে, আপনার জমি রাগী এবং টমেটোর জন্য ৯৪% উপযুক্ত।",
    dash_tasks: "খামারের কাজ (করণীয় তালিকা)",
    task_placeholder: "কাজের নাম লিখুন...",
    task_due: "নির্দিষ্ট তারিখ",
    btn_add_task: "কাজ যোগ করুন",
    no_tasks: "কোনো কাজ পেন্ডিং নেই! দিনটি উপভোগ করুন।",
    weather_title: "আবহাওয়া স্টেশন",
    weather_humidity: "আর্দ্রতা",
    weather_rainfall: "বৃষ্টিপাত",
    weather_rain_predict: "বৃষ্টির পূর্বাভাস",
    weather_alerts: "জরুরী সতর্কবার্তা",
    weather_no_alerts: "আপনার অঞ্চলে কোনো সতর্কবার্তা নেই।",
    weather_warning_rain: "আগামীকাল ভারী বৃষ্টির সম্ভাবনা আছে। সার ছিটানো এড়িয়ে চলুন।",
    market_title: "কৃষকদের বাজার",
    market_subtitle: "কৃষি সরঞ্জাম, বীজ, জৈব সার এবং তাজা ফসল কেনাবেচা করুন।",
    market_filter_all: "সব বিভাগ",
    market_filter_seeds: "বীজ",
    market_filter_fert: "সার",
    market_filter_tools: "কৃষি সরঞ্জাম",
    market_filter_crops: "ফসল",
    market_price: "মূল্য",
    market_seller: "বিক্রেতা",
    market_contact: "যোগাযোগ নম্বর",
    market_sell_item: "পণ্য তালিকাভুক্ত করুন",
    market_prod_name: "পণ্যের নাম",
    market_category: "বিভাগ",
    market_desc: "বিবরণ",
    market_list_success: "পণ্যটি সফলভাবে তালিকাভুক্ত করা হয়েছে!",
    scanner_title: "AI পাতা রোগ স্ক্যানার",
    scanner_subtitle: "পাতার রোগ শনাক্ত করতে এবং জৈব প্রতিকার জানতে পাতার ছবি আপলোড করুন।",
    scanner_drop: "আপলোড করতে ক্লিক করুন বা পাতার ছবিটি এখানে টেনে আনুন",
    scanner_btn: "পাতা বিশ্লেষণ করুন",
    scanner_result: "বিশ্লেষণ রিপোর্ট",
    scanner_confidence: "AI নির্ভুলতা",
    scanner_remedy: "রাসায়নিক প্রতিকার",
    scanner_organic: "জৈব প্রতিকার",
    search_title: "স্মার্ট কৃষি অনুসন্ধান",
    search_placeholder: "ফসলের নাম বা সরঞ্জামের কথা বলুন বা টাইপ করুন...",
    search_mic_listen: "শুনছি... এখন বলুন।",
    search_mic_error: "এই ব্রাউজারে ভয়েস অনুসন্ধান সমর্থন করে না।",
    search_results_crops: "সংশ্লিষ্ট ফসল ও রোগ",
    search_results_market: "বাজারের অফার",
    chat_header: "এগ্রিভার্স AI সহকারী",
    chat_welcome: "নমস্কার! আমি এগ্রিভার্স AI কৃষি সহকারী। আবহাওয়া বা পাতার রোগ সম্পর্কে জিজ্ঞেস করুন।",
    chat_placeholder: "আমাকে প্রশ্ন করুন...",
    faq_title: "সাধারণ জিজ্ঞাসা",
    contact_title: "এগ্রিভার্স সহায়তার সাথে যোগাযোগ করুন",
    contact_name: "নাম",
    contact_email: "ইমেইল",
    contact_msg: "বার্তা",
    contact_send: "বার্তা পাঠান",
    contact_success: "ধন্যবাদ! আমাদের সহায়তা দল শীঘ্রই আপনার সাথে যোগাযোগ করবে।"
  }
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('agriverse-lang') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('agriverse-lang', lang);
  }, [lang]);

  const t = (key) => {
    return translations[lang]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
